version: 2

updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    open-pull-requests-limit: 10

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    open-pull-requests-limit: 10
    groups:
      dev-changeset:
        applies-to: 'version-updates'
        dependency-type: 'development'
        patterns:
          - '@changesets/*'

      dev-code-checks:
        applies-to: 'version-updates'
        dependency-type: 'development'
        patterns:
          - '@marcalexiei/prettier-config'
          - '@marcalexiei/eslint-config'
          - 'eslint-doc-generator'
          - 'eslint-plugin-eslint-plugin'
          - 'eslint-plugin-n'
          - '@vitest/eslint-plugin'
          - 'knip'
          - 'prettier'
          - 'typescript'
          - typescript-eslint

      dev:
        applies-to: 'version-updates'
        dependency-type: 'development'
        patterns:
          - '@types/*'
          - '@typescript-eslint/rule-tester'
          - '@typescript-eslint/utils'
          - 'eslint'
          - 'vitest'
          - 'zshy'
